name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  PROJECT_NAME: OpenAI-Chat-Agent-Microservice
  
jobs:
  greeting_job:
      runs-on: ubuntu-latest
      env:
        Greeting: Hello
      steps:
        - name: "Say Hello Mona it's Monday"
          run: echo "$Greeting $First_Name. Happy Coding on the project $PROJECT_NAME!"
          env:
            First_Name: Subrata
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
